### ISSUE TITLE
How do I use this within the new Hugo Pipes PostCSS feature?

### ISSUE THREAD

**Issue by bwklein** [AaronJan/postcss-font-grabber#7]
I'm trying to integrate this into the PostCSS function of [Hugo Pipes](https://gohugo.io/hugo-pipes/postcss/#readout), more info [Here](https://regisphilibert.com/blog/2018/07/hugo-pipes-and-asset-processing-pipeline/).

Here is an example of the postcss.config.js file that I am using.
https://github.com/budparr/hugopipes-tailwindcss/blob/master/assets/css/postcss.config.js

I was hoping to integrate your plugin between @fullhuman/postcss-purgecss and autoprefixer.
Do you have suggestions on how to do this?

**Comment by AaronJan** [comment]
I didn't do any testing on Hugo Pipes, But I think this would be fine:

```javascript
class TailwindExtractor {
	static extract(content) {
		return content.match(/[A-z0-9-:\/]+/g)
	}
}

module.exports = {    
  plugins: [        
    require('postcss-import')({
      path: ["assets/css"],
    }), 
    require('tailwindcss')('./assets/css/tailwind.js'),
    require('@fullhuman/postcss-purgecss')({
      content: ['layouts/*.html'],
      extractors: [
      {
        extractor: TailwindExtractor,
        extensions: ['html']
      }], 
      fontFace: true,
      whitelist: ['class1', 'class2']
    }),    
    require('autoprefixer')({
      grid: true,
      browsers: ['>1%']
    }),    
    // PostCSS-Font-Grabber will use `from` and `to` options of `PostCSS`.
    require('postcss-font-grabber')(),   
  ]
}
```

Let me know if you have any further problem. 🤝

**Comment by bwklein** [comment]
Thank you,
I get the following error when I try to add the call to the font-grabber.

```
Building sites … TypeError: require(...) is not a function
    at Object.<anonymous> (D:\GitLab\TECi_Website\website\assets\config\postcss.config.js:31:36)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at requireFromString (D:\GitLab\TECi_Website\website\node_modules\require-from-string\index.js:28:4)
    at parseJsFile (D:\GitLab\TECi_Website\website\node_modules\cosmiconfig\dist\loadJs.js:15:15)
```

Here is my current postcss.config.js file.

```
class TailwindExtractor {
	static extract(content) {
		return content.match(/[A-z0-9-:\/]+/g)
	}
}

module.exports = {  
  plugins: [
    require('tailwindcss')('assets/config/tailwind.js'),

    require('@fullhuman/postcss-purgecss')({
      content: ['layouts/**/*.html'],
      css: ['public/css/*.css'],
      whitelistPatterns: [/pyrosim/,/pathfinder/,/petrasim/,/home/,/clean/,/open/,/slick/,/-mt-150/,/pb-150/,/search/],
      extractors: [
      {
        extractor: TailwindExtractor,
        extensions: ['html']
      }]
    }),
       
    require('autoprefixer')({
      grid: true,
      browsers: ['>1%']
    }),

    // PostCSS-Font-Grabber will use `from` and `to` options of `PostCSS`.
    require('postcss-font-grabber')({dirPath: 'public/css/'})
  ]
}
```

**Comment by cybervaldez** [comment]
on top:
let { postcssFontGrabber } = require('postcss-font-grabber');

then replace
require('postcss-font-grabber')({dirPath: 'public/css/'})
with
postcssFontGrabber({dirPath: 'public/css/'})

**Comment by AaronJan** [comment]
Close due to outdated.
